spring.application.name=sylektus

# MySQL Connection
spring.datasource.url=jdbc:mysql://nozomi.proxy.rlwy.net:18476/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=NZaoxLCnUCPGwNWKryTqsVBFfwISDZMy
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# MySQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


server.port=8080


#Email Message

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=krishsisodiya7389@gmail.com
spring.mail.password=faxy zglk jlgn hvvr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
